/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_surelution_tc400_Driver */

#ifndef _Included_com_surelution_tc400_Driver
#define _Included_com_surelution_tc400_Driver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_surelution_tc400_Driver
 * Method:    RegisterUSB
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_surelution_tc400_Driver_RegisterUSB
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_surelution_tc400_Driver
 * Method:    GetDeviceInfo
 * Signature: (ILcom/surelution/tc400/DeviceInfo;)I
 */
JNIEXPORT jint JNICALL Java_com_surelution_tc400_Driver_GetDeviceInfo
  (JNIEnv *, jclass, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
